name: Express.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]

  workflow_dispatch:
env:
  SPEECH2TEXT_API_KEY: ${{secrets.SPEECH2TEXT_API_KEY}}
  SPEECH2TEXT_SERVICE_URL: ${{secrets.SPEECH2TEXT_SERVICE_URL}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - run: npm ci
      - run: npm test
      - run: npm run lint
      - run: npm run format
      
